### ISSUE TITLE
temp_looping issue on windows_7

### ISSUE THREAD

**Issue by AngelinaAngel** [karthik558/clean-windows#1]
Seems like this line acting weird on windows-7. Tested on windows 10 and it was just fine..

https://github.com/karthik558/clean-windows/blob/936c2f160d8d0225257ed8526b3d4911bd8fade6/clean-win.bat#L348

Please check this issue !

**Comment by karthik558** [comment]
This issue was actually rectified long ago (For Windows 10) 
`
https://github.com/karthik558/clean-windows/commit/510a3e8daf8d5054538dadd7391afe7e2702b8ad
`
Let me know if you are using my latest release tool or not, if its latest release then i will try it on my virtual_windows_7 machine and will check that issue.

Or else can u please give me a log file? it will be much appreciated.

**Comment by AngelinaAngel** [comment]
I am using the cpp one, is that the problem ?

**Comment by karthik558** [comment]
> I am using the cpp one, is that the problem ?

Yes, that's the problem, i haven't made the cpp one stable, Will update it ASAP.

**Comment by karthik558** [comment]
Fixed !
